[build]
  publish = "public"
  command = "hugo --gc --minify -b $URL"

[context.production.environment]
  HUGO_VERSION = "0.146.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify -b $URL"

[[redirects]]
  from = "/_redirects"
  to = "/"
  status = 200
